services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  chat:
    build:
      context: .
      dockerfile: docker/Dockerfile.chat
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./.chainlit:/app/.chainlit
