FROM public.ecr.aws/lambda/python:3.11

COPY pyproject.toml ${LAMBDA_TASK_ROOT}/
COPY src/ ${LAMBDA_TASK_ROOT}/src/

RUN pip install --no-cache-dir .

CMD ["agentic_ai.lambda_handlers.action_group_handler.handler"]
